name: Publish to GH Pages

on:
  push:
    branches:
      - main
  pull_request: # just for testing

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'sarayourfriend/openverse-overvue' }}

    steps:
      - uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.30.1
          # Set this to false because we want to be able to skip installation if there is a cache hit in the next step
          run_install: false

      # setup node.js environment and npm
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: "pnpm"

      - name: Build website
        run: pnpm install && pnpm build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@bbdfb200618d235585ad98e965f4aafc39b4c501 # v3.7.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          force_orphan: true
